name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4. Roda os testes do Cypress com geração de screenshots e vídeos
      - name: Run Cypress tests
        run: npm run cypress:run

      # 5. Upload de relatórios Mochawesome
      - name: Upload Cypress test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/reports

      # 6. Upload de screenshots (apenas se houver falhas)
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 7. Upload de vídeos (apenas se houver falhas)
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
