name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4. Roda os testes do Cypress em modo headless e gera Mochawesome
      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome --headless --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false

      # 5. Upload de relatórios Mochawesome (apenas se existirem)
      - name: Upload Cypress test reports
        if: always() && hashFiles('cypress/reports/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/reports

      # 6. Upload de screenshots (apenas se existirem)
      - name: Upload Cypress screenshots
        if: always() && hashFiles('cypress/screenshots/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 7. Upload de vídeos (apenas se existirem)
      - name: Upload Cypress videos
        if: always() && hashFiles('cypress/videos/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
